# 指定启动的服务名称:
services:
  - name: learner
    path: 'examples/dqn/learner.py'
    num: 3
    kwargs:
      lr: 0.0001
      batchsize: 30

  - name: actor
    path: 'examples/dqn/actor.py'
    num: 2

# 指定需要启动的环境

envs:
  - name: env
    path: 'examples/dqn/env.py'
    num: 2

log_dir: './log'

is_distributed: True
is_head: True


